# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0002_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='campo',
            field=models.TextField(),
        ),
    ]
