# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0003_auto_20180503_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='row_data',
            name='id_articulo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
