# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0004_row_data_id_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='row_data',
            name='contenido2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
