# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0005_row_data_contenido2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row_data',
            name='contenido2',
        ),
    ]
