# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0010_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.TextField()),
                ('Row_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egmapp.Row_data')),
            ],
        ),
    ]
