# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0011_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Row_data',
        ),
        migrations.AddField(
            model_name='categoria',
            name='Mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egmapp.Mapa'),
        ),
    ]
