# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0012_auto_20180504_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Mapa',
        ),
        migrations.AddField(
            model_name='mapa',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egmapp.Categoria'),
        ),
    ]
