# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0013_auto_20180504_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Row_data',
        ),
    ]
