# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0014_delete_row_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.TextField()),
                ('contenido', models.TextField()),
            ],
        ),
    ]
