# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0015_row_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Mapa',
        ),
    ]
