# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0016_auto_20180521_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.TextField()),
                ('etiquetas', models.TextField()),
                ('codigo', models.TextField()),
            ],
        ),
    ]
