# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0017_codigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('campo', models.TextField()),
                ('tipo', models.TextField()),
                ('pregunta', models.TextField()),
                ('longitud', models.IntegerField()),
                ('pinicial', models.IntegerField()),
                ('pfinal', models.IntegerField()),
            ],
        ),
    ]
