# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0018_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='Codigos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egmapp.Codigos'),
        ),
    ]
