# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0020_auto_20180521_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='preguntas',
        ),
    ]
