# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egmapp', '0021_remove_mapa_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
